# Generated by Django 4.0.2 on 2022-02-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='client',
        ),
        migrations.AddField(
            model_name='department',
            name='clients',
            field=models.ManyToManyField(related_name='departments', to='customers.Client', verbose_name='Clients'),
        ),
    ]
